---
- name: reboot module demo
  hosts: [datacenter]
  become : true
  tasks:
    - name : reboot host
      ansible.builtin.reboot:
         msg : "ansible reboot"
         pre_reboot_delay: 5
         post_reboot_delay: 10
         test_command: "whoami"


         
